-- Starter character templates for Journey to the Inner World (5 characters).
-- Follows 20260103_seed_starter_character_templates.sql. Re-runnable: ON CONFLICT upsert on
-- unique_template_per_campaign (starter_campaign_id, template_key).
-- Not yet applied to prod; Hetzner applies on Rob's line (#2225), after the campaign is ingested.
-- Each row is INSERT ... SELECT FROM starter_campaigns: a no-op where the campaign row is missing
-- (fresh replay), an upsert where it exists. No portrait_url: the asset uploader sets it.
-- Classes are SRD only (starter seeding rejects non-SRD classes). Races use the app's names.

-- 1. The Driller (Dwarf Fighter)
INSERT INTO public.starter_character_templates (
  starter_campaign_id,
  template_key,
  name,
  tagline,
  race,
  subrace,
  class,
  background,
  level,
  ability_scores,
  personality,
  skills,
  languages,
  equipment,
  adapted_backstory,
  campaign_hook,
  portrait_prompt,
  display_order
) SELECT
  id,
  'the-driller',
  'The Driller',
  'Guild drill-crew veteran who has heard the rock scream',
  'Dwarf',
  'Hill Dwarf',
  'Fighter',
  'Guild Artisan',
  1,
  '{"strength": 17, "dexterity": 10, "constitution": 16, "intelligence": 12, "wisdom": 13, "charisma": 8}',
  '{"traits": ["I judge rock by its sound before I trust it with my weight", "I name every machine I work on and apologise when I break one"], "ideals": ["Craft. A job done right is the only prayer I trust"], "bonds": ["Three of my crew went down the first shaft and never came up"], "flaws": ["I will not leave a machine behind, even when I should"]}',
  '["athletics", "perception", "insight", "persuasion"]',
  '["Common", "Dwarvish", "Undercommon"]',
  '["chain mail", "warhammer", "shield", "light crossbow", "dungeoneer''s pack", "brass drill-bit pendant"]',
  'Fifteen years on the Delvers'' Guild drill crews taught me that stone talks, if you listen. The week before the quake, every drill in the district started to ring with the same low note, and the foremen laughed at me for saying so. Then the ground opened and swallowed half the town. Baron Finch pays well, and I am the best drill-hand he has. But I did not sign on for the money.',
  'The Guild''s great drill is the only way through the Progenitor''s Gate, and it answers to me. Somewhere below, the note the rock was singing is getting louder. I want to find out what is singing it before it brings the rest of the world down.',
  'Stocky hill dwarf in scuffed chain mail under a canvas work coat, brass goggles pushed up on a soot-streaked forehead, braided beard tied with copper wire, warhammer over one shoulder, a brass drill-bit pendant at the throat, warm lantern light from below, amber and brass palette, strong silhouette, face in the upper middle of the frame',
  1
FROM public.starter_campaigns
WHERE id = 'journey-to-the-inner-world'
ON CONFLICT (starter_campaign_id, template_key) DO UPDATE SET
  name = EXCLUDED.name,
  tagline = EXCLUDED.tagline,
  race = EXCLUDED.race,
  subrace = EXCLUDED.subrace,
  class = EXCLUDED.class,
  background = EXCLUDED.background,
  level = EXCLUDED.level,
  ability_scores = EXCLUDED.ability_scores,
  personality = EXCLUDED.personality,
  skills = EXCLUDED.skills,
  languages = EXCLUDED.languages,
  equipment = EXCLUDED.equipment,
  adapted_backstory = EXCLUDED.adapted_backstory,
  campaign_hook = EXCLUDED.campaign_hook,
  portrait_prompt = EXCLUDED.portrait_prompt,
  display_order = EXCLUDED.display_order,
  updated_at = now();

-- 2. The Surveyor (Human Wizard)
INSERT INTO public.starter_character_templates (
  starter_campaign_id,
  template_key,
  name,
  tagline,
  race,
  subrace,
  class,
  background,
  level,
  ability_scores,
  personality,
  skills,
  languages,
  equipment,
  adapted_backstory,
  campaign_hook,
  portrait_prompt,
  display_order
) SELECT
  id,
  'the-surveyor',
  'The Surveyor',
  'Maps the places that refuse to hold still',
  'Human',
  NULL,
  'Wizard',
  'Sage',
  1,
  '{"strength": 9, "dexterity": 15, "constitution": 14, "intelligence": 16, "wisdom": 13, "charisma": 11}',
  '{"traits": ["I measure everything twice and still do not trust the answer", "I talk to my instruments when I am frightened"], "ideals": ["Knowledge. A true map saves more lives than a sword"], "bonds": ["My survey notes are the only record of a village that no longer exists"], "flaws": ["I will walk into danger to fill a blank space on a map"]}',
  '["arcana", "history", "investigation", "insight"]',
  '["Common", "Dwarvish", "Draconic", "Elvish"]',
  '["quarterstaff", "component pouch", "spellbook", "scholar''s pack", "brass survey theodolite", "waxed map case"]',
  'I was the district''s surveyor: property lines, mine shafts, the odd flooded cellar. My maps were perfect until the night of the quake, when the ground I had measured for ten years folded in on itself. Now the Guild wants a chart of the Great Chasm, and nobody else can read a theodolite by lantern light.',
  'The Baron wants a route to the Inner World''s riches. I want the first true map of a place where distances lie and gravity changes its mind. If the Labyrinth of Echoes can be charted, I will chart it.',
  'Lean human scholar in a weathered oilskin coat covered in pockets, a brass theodolite strapped to the back, ink-stained fingers holding a half-finished map, spectacles with a cracked lens, a faint blue arcane glow at the fingertips, cold daylight from far above mixed with lantern amber, strong silhouette, face in the upper middle of the frame',
  2
FROM public.starter_campaigns
WHERE id = 'journey-to-the-inner-world'
ON CONFLICT (starter_campaign_id, template_key) DO UPDATE SET
  name = EXCLUDED.name,
  tagline = EXCLUDED.tagline,
  race = EXCLUDED.race,
  subrace = EXCLUDED.subrace,
  class = EXCLUDED.class,
  background = EXCLUDED.background,
  level = EXCLUDED.level,
  ability_scores = EXCLUDED.ability_scores,
  personality = EXCLUDED.personality,
  skills = EXCLUDED.skills,
  languages = EXCLUDED.languages,
  equipment = EXCLUDED.equipment,
  adapted_backstory = EXCLUDED.adapted_backstory,
  campaign_hook = EXCLUDED.campaign_hook,
  portrait_prompt = EXCLUDED.portrait_prompt,
  display_order = EXCLUDED.display_order,
  updated_at = now();

-- 3. The Lamplighter (Halfling Rogue)
INSERT INTO public.starter_character_templates (
  starter_campaign_id,
  template_key,
  name,
  tagline,
  race,
  subrace,
  class,
  background,
  level,
  ability_scores,
  personality,
  skills,
  languages,
  equipment,
  adapted_backstory,
  campaign_hook,
  portrait_prompt,
  display_order
) SELECT
  id,
  'the-lamplighter',
  'The Lamplighter',
  'Grew up in the shafts; knows every way out',
  'Halfling',
  'Lightfoot Halfling',
  'Rogue',
  'Urchin',
  1,
  '{"strength": 8, "dexterity": 17, "constitution": 14, "intelligence": 12, "wisdom": 10, "charisma": 14}',
  '{"traits": ["I count exits in every room without meaning to", "I keep a lantern lit even when I sleep"], "ideals": ["Community. Nobody gets left in the dark"], "bonds": ["My street fell into the chasm. Some of my neighbours are still down there"], "flaws": ["I take things that are not mine and call it salvage"]}',
  '["acrobatics", "stealth", "sleight_of_hand", "perception"]',
  '["Common", "Halfling"]',
  '["shortsword", "shortbow", "quiver with 20 arrows", "leather armor", "thieves'' tools", "burglar''s pack", "hooded lantern"]',
  'I lit the lamps in the old mine shafts under town, for a copper a shift and all the candle-ends I could carry. I know the tunnels better than the men who dug them. When the quake came, my whole street slid into the new chasm, lamps still burning. I saw lights down there afterwards. Lights that were not ours.',
  'The Guild needs someone small, quick and unafraid of the dark to run the rope-bridges. I need to know whose lights I saw. If any of my neighbours are alive down there, I am going to bring them home.',
  'Quick-eyed halfling in patched leather armour and a soot-dark hood, a lit hooded lantern held up at arm''s length, shortsword at the hip, a coil of rope over one shoulder, grinning with a gap in her teeth, warm lantern glow against a dark shaft, amber and soot-grey palette, strong silhouette, face in the upper middle of the frame',
  3
FROM public.starter_campaigns
WHERE id = 'journey-to-the-inner-world'
ON CONFLICT (starter_campaign_id, template_key) DO UPDATE SET
  name = EXCLUDED.name,
  tagline = EXCLUDED.tagline,
  race = EXCLUDED.race,
  subrace = EXCLUDED.subrace,
  class = EXCLUDED.class,
  background = EXCLUDED.background,
  level = EXCLUDED.level,
  ability_scores = EXCLUDED.ability_scores,
  personality = EXCLUDED.personality,
  skills = EXCLUDED.skills,
  languages = EXCLUDED.languages,
  equipment = EXCLUDED.equipment,
  adapted_backstory = EXCLUDED.adapted_backstory,
  campaign_hook = EXCLUDED.campaign_hook,
  portrait_prompt = EXCLUDED.portrait_prompt,
  display_order = EXCLUDED.display_order,
  updated_at = now();

-- 4. The Chaplain (Human Cleric)
INSERT INTO public.starter_character_templates (
  starter_campaign_id,
  template_key,
  name,
  tagline,
  race,
  subrace,
  class,
  background,
  level,
  ability_scores,
  personality,
  skills,
  languages,
  equipment,
  adapted_backstory,
  campaign_hook,
  portrait_prompt,
  display_order
) SELECT
  id,
  'the-chaplain',
  'The Chaplain',
  'His chapel fell into the chasm; he followed it down',
  'Human',
  NULL,
  'Cleric',
  'Acolyte',
  1,
  '{"strength": 14, "dexterity": 11, "constitution": 15, "intelligence": 9, "wisdom": 16, "charisma": 13}',
  '{"traits": ["I bless every rope before anyone climbs it", "I listen more than I preach, and people notice"], "ideals": ["Faith. Nothing that lives is beyond care, not even what lives below"], "bonds": ["The chapel bell went down with the building. I mean to ring it again"], "flaws": ["I argue with anyone who calls the Inner World a hell, including myself"]}',
  '["medicine", "religion", "insight", "persuasion"]',
  '["Common", "Celestial", "Dwarvish", "Elvish"]',
  '["mace", "scale mail", "shield", "holy symbol", "priest''s pack", "chapel bell clapper"]',
  'I kept the little chapel on the hill above the mines. When the quake split the town, the chapel and its graveyard slid into the chasm whole. Elder Maeve of the Surface Sentinels says the passages must be sealed and everyone below given up for lost. I buried half those people. I will not give them up without seeing for myself.',
  'The Sentinels call the expedition a sin, and the Baron calls it business. I think it is a pilgrimage. If something is being born at the heart of the world, somebody should be there who can tell a birth from a death.',
  'Broad-shouldered human priest in dented scale mail over a grey travelling cassock, a holy symbol on a leather cord, a heavy iron bell clapper tied at the belt, kind tired eyes, mace in hand, warm lantern light and grey daylight from above, slate and amber palette, strong silhouette, face in the upper middle of the frame',
  4
FROM public.starter_campaigns
WHERE id = 'journey-to-the-inner-world'
ON CONFLICT (starter_campaign_id, template_key) DO UPDATE SET
  name = EXCLUDED.name,
  tagline = EXCLUDED.tagline,
  race = EXCLUDED.race,
  subrace = EXCLUDED.subrace,
  class = EXCLUDED.class,
  background = EXCLUDED.background,
  level = EXCLUDED.level,
  ability_scores = EXCLUDED.ability_scores,
  personality = EXCLUDED.personality,
  skills = EXCLUDED.skills,
  languages = EXCLUDED.languages,
  equipment = EXCLUDED.equipment,
  adapted_backstory = EXCLUDED.adapted_backstory,
  campaign_hook = EXCLUDED.campaign_hook,
  portrait_prompt = EXCLUDED.portrait_prompt,
  display_order = EXCLUDED.display_order,
  updated_at = now();

-- 5. The Echo (Ravenfolk Bard)
INSERT INTO public.starter_character_templates (
  starter_campaign_id,
  template_key,
  name,
  tagline,
  race,
  subrace,
  class,
  background,
  level,
  ability_scores,
  personality,
  skills,
  languages,
  equipment,
  adapted_backstory,
  campaign_hook,
  portrait_prompt,
  display_order
) SELECT
  id,
  'the-echo',
  'The Echo',
  'A ravenfolk mimic chasing the song beneath the mountains',
  'Ravenfolk',
  NULL,
  'Bard',
  'Entertainer',
  1,
  '{"strength": 8, "dexterity": 16, "constitution": 13, "intelligence": 10, "wisdom": 13, "charisma": 15}',
  '{"traits": ["I answer questions in other people''s voices", "I collect sounds the way others collect coins"], "ideals": ["Beauty. Every sound deserves to be heard once more"], "bonds": ["I heard the mountains sing a year ago, and I have not slept well since"], "flaws": ["I will risk anything for a sound I have never heard"]}',
  '["acrobatics", "performance", "deception", "perception"]',
  '["Common", "Auran"]',
  '["rapier", "leather armor", "dagger", "lute", "entertainer''s pack", "sound-shell that replays one sound"]',
  'Ravenfolk speak with borrowed voices; that is our gift and our curse. I made a living on the town stage mimicking storms, lovers and the mayor. Then came the Day the Mountains Sang, one pure note from every peak at once, and I could not copy it. It is the only sound I have ever failed to catch.',
  'The note is coming from below. The Echo-Thieves would sell their own voices to record it, and so would I. The Guild''s expedition is the fastest way down, and a performer is always welcome at a lonely camp.',
  'Slender ravenfolk bard with glossy black feathers and a sharp dark beak, bright curious eyes, a patched performer''s coat over leather armour, a lute on the back, holding up a spiral sound-shell with faint visible sound rings around it, magenta and violet accent light, strong silhouette, face in the upper middle of the frame',
  5
FROM public.starter_campaigns
WHERE id = 'journey-to-the-inner-world'
ON CONFLICT (starter_campaign_id, template_key) DO UPDATE SET
  name = EXCLUDED.name,
  tagline = EXCLUDED.tagline,
  race = EXCLUDED.race,
  subrace = EXCLUDED.subrace,
  class = EXCLUDED.class,
  background = EXCLUDED.background,
  level = EXCLUDED.level,
  ability_scores = EXCLUDED.ability_scores,
  personality = EXCLUDED.personality,
  skills = EXCLUDED.skills,
  languages = EXCLUDED.languages,
  equipment = EXCLUDED.equipment,
  adapted_backstory = EXCLUDED.adapted_backstory,
  campaign_hook = EXCLUDED.campaign_hook,
  portrait_prompt = EXCLUDED.portrait_prompt,
  display_order = EXCLUDED.display_order,
  updated_at = now();
