-- Starter character templates for The Impossible Vault (5 characters).
-- Follows 20260103_seed_starter_character_templates.sql. Re-runnable: ON CONFLICT upsert on
-- unique_template_per_campaign (starter_campaign_id, template_key).
-- Applied to prod by the Hetzner ingest session on 2026-09-29; see #2226 / #2276 / #2288.
-- This file records that data change and replays it safely.
-- Each row is INSERT ... SELECT FROM starter_campaigns: a no-op where the campaign row is missing
-- (fresh replay), an upsert where it exists. No portrait_url: the asset uploader sets it.
-- Classes are SRD only (starter seeding rejects non-SRD classes). Races use the app's names.

-- 1. The Cardsharp (Half-Elf Bard)
INSERT INTO public.starter_character_templates (
  starter_campaign_id,
  template_key,
  name,
  tagline,
  race,
  subrace,
  class,
  background,
  level,
  ability_scores,
  personality,
  skills,
  languages,
  equipment,
  adapted_backstory,
  campaign_hook,
  portrait_prompt,
  display_order
) SELECT
  id,
  'the-cardsharp',
  'The Cardsharp',
  'Never cheated a hand in their life. Never needed to.',
  'Half-Elf',
  NULL,
  'Bard',
  'Charlatan',
  1,
  '{"strength": 8, "dexterity": 14, "constitution": 12, "intelligence": 12, "wisdom": 10, "charisma": 17}',
  '{"traits": ["I shuffle a deck when I am thinking, and I am always thinking", "I remember every face that ever lost to me"], "ideals": ["Style. If you win ugly, the house wins anyway"], "bonds": ["Old Ivory dealt my first high-stakes hand and let me win it. I want to know why"], "flaws": ["I cannot walk past a game I think I can beat"]}',
  '["deception", "persuasion", "sleight_of_hand", "insight"]',
  '["Common", "Elvish", "Halfling"]',
  '["rapier", "dagger", "leather armor", "lute", "disguise kit", "entertainer''s pack", "deck of marked cards"]',
  'I learned cards in the back rooms of Glimmerfall, where the tables are crooked and the dealers are worse. I never cheated. I watched. I learned the tells of every dealer on the Gaming Floor except one: Old Ivory, who has not smiled in three hundred years. The Velvet Cord invites me to their games because I make the rich look interesting. They do not know I keep a list of everything they say.',
  'Tonight a stranger sat down at my table and dealt me a card I did not shuffle in: a Weeping Ace. His name is Darian Ashcombe. He says he needs an eleventh pair of hands, and that mine are the best in the city. I want to know how the card got into my deck.',
  'Half-elf card player in a sharp waistcoat with the sleeves rolled, long fingers fanning a deck of cards, one card showing a weeping face, sitting at a green felt table under warm lamplight, a knowing half-smile, neon teal glow from a window behind',
  1
FROM public.starter_campaigns
WHERE id = 'the-impossible-vault'
ON CONFLICT (starter_campaign_id, template_key) DO UPDATE SET
  name = EXCLUDED.name,
  tagline = EXCLUDED.tagline,
  race = EXCLUDED.race,
  subrace = EXCLUDED.subrace,
  class = EXCLUDED.class,
  background = EXCLUDED.background,
  level = EXCLUDED.level,
  ability_scores = EXCLUDED.ability_scores,
  personality = EXCLUDED.personality,
  skills = EXCLUDED.skills,
  languages = EXCLUDED.languages,
  equipment = EXCLUDED.equipment,
  adapted_backstory = EXCLUDED.adapted_backstory,
  campaign_hook = EXCLUDED.campaign_hook,
  portrait_prompt = EXCLUDED.portrait_prompt,
  display_order = EXCLUDED.display_order,
  updated_at = now();

-- 2. The Cracksman (Halfling Rogue)
INSERT INTO public.starter_character_templates (
  starter_campaign_id,
  template_key,
  name,
  tagline,
  race,
  subrace,
  class,
  background,
  level,
  ability_scores,
  personality,
  skills,
  languages,
  equipment,
  adapted_backstory,
  campaign_hook,
  portrait_prompt,
  display_order
) SELECT
  id,
  'the-cracksman',
  'The Cracksman',
  'No lock in Glimmerfall has said no to them. Yet.',
  'Halfling',
  'Lightfoot Halfling',
  'Rogue',
  'Criminal',
  1,
  '{"strength": 8, "dexterity": 17, "constitution": 13, "intelligence": 14, "wisdom": 12, "charisma": 10}',
  '{"traits": ["I listen to a lock before I touch it", "I always know three ways out of any room"], "ideals": ["Craft. A clean job is a work of art"], "bonds": ["Madame Fortuna gave me my first set of picks, and she will want them back one day"], "flaws": ["I cannot resist a lock that someone calls unbreakable"]}',
  '["stealth", "sleight_of_hand", "investigation", "perception"]',
  '["Common", "Halfling"]',
  '["leather armor", "shortsword", "shortbow", "arrows (20)", "thieves'' tools", "burglar''s pack", "crowbar"]',
  'I grew up in the Sewers of Whispers, running messages for the Underworld Alliance. Madame Fortuna noticed I could open anything with a hinge. By fifteen I had cracked every strongbox on the Rustwater Docks. I have never been caught. I have also never tried the one lock everyone talks about: the Vault of Stars.',
  'A man named Darian Ashcombe found me in a gambling den and dealt me a Weeping Ace before I sat down. He says the Vault of Stars can be opened, and that he has a plan. Madame Fortuna says he is a dead man walking. I want to see the lock before he dies.',
  'Small halfling burglar in a dark close-fitting coat with many pockets, a ring of fine lockpicks between the fingers, ear pressed to the brass dial of a huge ornate vault door, eyes closed in concentration, a single lantern below lighting the face from underneath',
  2
FROM public.starter_campaigns
WHERE id = 'the-impossible-vault'
ON CONFLICT (starter_campaign_id, template_key) DO UPDATE SET
  name = EXCLUDED.name,
  tagline = EXCLUDED.tagline,
  race = EXCLUDED.race,
  subrace = EXCLUDED.subrace,
  class = EXCLUDED.class,
  background = EXCLUDED.background,
  level = EXCLUDED.level,
  ability_scores = EXCLUDED.ability_scores,
  personality = EXCLUDED.personality,
  skills = EXCLUDED.skills,
  languages = EXCLUDED.languages,
  equipment = EXCLUDED.equipment,
  adapted_backstory = EXCLUDED.adapted_backstory,
  campaign_hook = EXCLUDED.campaign_hook,
  portrait_prompt = EXCLUDED.portrait_prompt,
  display_order = EXCLUDED.display_order,
  updated_at = now();

-- 3. The Bouncer (Half-Orc Fighter)
INSERT INTO public.starter_character_templates (
  starter_campaign_id,
  template_key,
  name,
  tagline,
  race,
  subrace,
  class,
  background,
  level,
  ability_scores,
  personality,
  skills,
  languages,
  equipment,
  adapted_backstory,
  campaign_hook,
  portrait_prompt,
  display_order
) SELECT
  id,
  'the-bouncer',
  'The Bouncer',
  'Guarded the Casino door for ten years. Then the Silence took their partner.',
  'Half-Orc',
  NULL,
  'Fighter',
  'Soldier',
  1,
  '{"strength": 17, "dexterity": 12, "constitution": 15, "intelligence": 10, "wisdom": 13, "charisma": 9}',
  '{"traits": ["I stand between trouble and anyone smaller than me", "I say little, and I mean all of it"], "ideals": ["Loyalty. You protect your people, even from your employer"], "bonds": ["My partner on the door vanished in the Silence of the Slots. Commander Vex told me to forget it. I did not"], "flaws": ["I trust my fists more than any plan"]}',
  '["athletics", "intimidation", "perception", "insight"]',
  '["Common", "Orc"]',
  '["chain mail", "longsword", "shield", "light crossbow", "crossbow bolts (20)", "explorer''s pack"]',
  'For ten years I stood at the Grand Celestial Casino''s front door under Commander Vex. I threw out cheats and carried out drunks. Ten years ago, during the Silence of the Slots, my partner was on the gaming floor. When the machines started again, she was gone. The Casino called it a discharge. They gave me a medal and a pay rise to stop asking. I quit the next day.',
  'A stranger named Darian Ashcombe says he knows where the four hundred went. He dealt me a Weeping Ace, the same card my partner drew the night before she vanished. I do not trust him. I do not have to. I only have to follow him to the vault.',
  'Broad half-orc guard in a dented chain mail coat under a torn casino uniform jacket, a longsword on the back, arms folded, standing in a rain-wet neon-lit alley, jaw set, a small tarnished medal pinned upside down on the chest',
  3
FROM public.starter_campaigns
WHERE id = 'the-impossible-vault'
ON CONFLICT (starter_campaign_id, template_key) DO UPDATE SET
  name = EXCLUDED.name,
  tagline = EXCLUDED.tagline,
  race = EXCLUDED.race,
  subrace = EXCLUDED.subrace,
  class = EXCLUDED.class,
  background = EXCLUDED.background,
  level = EXCLUDED.level,
  ability_scores = EXCLUDED.ability_scores,
  personality = EXCLUDED.personality,
  skills = EXCLUDED.skills,
  languages = EXCLUDED.languages,
  equipment = EXCLUDED.equipment,
  adapted_backstory = EXCLUDED.adapted_backstory,
  campaign_hook = EXCLUDED.campaign_hook,
  portrait_prompt = EXCLUDED.portrait_prompt,
  display_order = EXCLUDED.display_order,
  updated_at = now();

-- 4. The Chaplain (Human Cleric)
INSERT INTO public.starter_character_templates (
  starter_campaign_id,
  template_key,
  name,
  tagline,
  race,
  subrace,
  class,
  background,
  level,
  ability_scores,
  personality,
  skills,
  languages,
  equipment,
  adapted_backstory,
  campaign_hook,
  portrait_prompt,
  display_order
) SELECT
  id,
  'the-chaplain',
  'The Chaplain',
  'Keeps four hundred candles lit for people the city forgot.',
  'Human',
  NULL,
  'Cleric',
  'Acolyte',
  1,
  '{"strength": 12, "dexterity": 10, "constitution": 14, "intelligence": 10, "wisdom": 17, "charisma": 13}',
  '{"traits": ["I bless every coin before I spend it", "I learn the name of everyone I meet, and I pray for them by name"], "ideals": ["Mercy. Luck should belong to the people who make it"], "bonds": ["The Chip Widows took me in when my temple of the Goddess of Fortune closed its doors"], "flaws": ["I believe every omen, even the ones that lie"]}',
  '["medicine", "religion", "insight", "persuasion"]',
  '["Common", "Celestial", "Dwarvish"]',
  '["scale mail", "mace", "shield", "holy symbol", "priest''s pack", "light crossbow", "crossbow bolts (20)"]',
  'I was an acolyte at a small temple of the Goddess of Fortune. When the Casino began to drink the city''s luck, our congregation stopped coming. The temple closed. The Chip Widows gave me a place at their chapel, and now I keep four hundred candles lit, one for each person lost in the Silence of the Slots. Every year someone nails a folded Weeping Ace to the Casino doors. Every year I bless it.',
  'Tonight the Weeping Ace was not on the Casino door. It was in my hand, dealt to me by a man named Darian Ashcombe. He asked if I still believed the four hundred could come home. I said yes before I could stop myself.',
  'Human cleric in plain grey vestments over scale mail, a small golden coin-shaped holy symbol at the neck, holding a lit candle in cupped hands inside a dim chapel of hundreds of candle stubs, calm and kind face, warm candlelight',
  4
FROM public.starter_campaigns
WHERE id = 'the-impossible-vault'
ON CONFLICT (starter_campaign_id, template_key) DO UPDATE SET
  name = EXCLUDED.name,
  tagline = EXCLUDED.tagline,
  race = EXCLUDED.race,
  subrace = EXCLUDED.subrace,
  class = EXCLUDED.class,
  background = EXCLUDED.background,
  level = EXCLUDED.level,
  ability_scores = EXCLUDED.ability_scores,
  personality = EXCLUDED.personality,
  skills = EXCLUDED.skills,
  languages = EXCLUDED.languages,
  equipment = EXCLUDED.equipment,
  adapted_backstory = EXCLUDED.adapted_backstory,
  campaign_hook = EXCLUDED.campaign_hook,
  portrait_prompt = EXCLUDED.portrait_prompt,
  display_order = EXCLUDED.display_order,
  updated_at = now();

-- 5. The Luck Scholar (Gnome Wizard)
INSERT INTO public.starter_character_templates (
  starter_campaign_id,
  template_key,
  name,
  tagline,
  race,
  subrace,
  class,
  background,
  level,
  ability_scores,
  personality,
  skills,
  languages,
  equipment,
  adapted_backstory,
  campaign_hook,
  portrait_prompt,
  display_order
) SELECT
  id,
  'the-luck-scholar',
  'The Luck Scholar',
  'Expelled from the City Archives for asking where the luck goes.',
  'Gnome',
  'Rock Gnome',
  'Wizard',
  'Sage',
  1,
  '{"strength": 8, "dexterity": 14, "constitution": 13, "intelligence": 17, "wisdom": 12, "charisma": 10}',
  '{"traits": ["I carry a notebook of odds for things nobody else measures", "I cannot finish a sentence when I am close to an answer"], "ideals": ["Truth. Every number hides a story, and every story hides a number"], "bonds": ["My mentor in the City Archives disappeared after she wrote a paper on Chance-Matter"], "flaws": ["I will risk anything to test a theory"]}',
  '["arcana", "history", "investigation", "insight"]',
  '["Common", "Gnomish", "Draconic", "Celestial"]',
  '["quarterstaff", "dagger", "component pouch", "spellbook", "scholar''s pack", "brass magnifying loupe"]',
  'I studied Chance-Matter in the City Archives, where the reading rooms move at night. My mentor proved that the Casino takes more luck than the city could ever spend. Then her paper vanished, and so did she. The Accountants of Zero asked me to join them. The Archives asked me to leave. I did both, in that order, and then I left the Accountants too.',
  'A man named Darian Ashcombe found me at a card table, working out the odds on a machine that had not paid out in ten years. He dealt me a Weeping Ace and told me the odds of that card were zero. He was right. I want to know what else in that vault breaks the math.',
  'Small rock gnome scholar with wild hair, round brass spectacles and ink-stained fingers, clutching a notebook full of numbers, a thin thread of glowing liquid gold floating above an open palm, standing among tall shelves in a dim archive, bright curious eyes',
  5
FROM public.starter_campaigns
WHERE id = 'the-impossible-vault'
ON CONFLICT (starter_campaign_id, template_key) DO UPDATE SET
  name = EXCLUDED.name,
  tagline = EXCLUDED.tagline,
  race = EXCLUDED.race,
  subrace = EXCLUDED.subrace,
  class = EXCLUDED.class,
  background = EXCLUDED.background,
  level = EXCLUDED.level,
  ability_scores = EXCLUDED.ability_scores,
  personality = EXCLUDED.personality,
  skills = EXCLUDED.skills,
  languages = EXCLUDED.languages,
  equipment = EXCLUDED.equipment,
  adapted_backstory = EXCLUDED.adapted_backstory,
  campaign_hook = EXCLUDED.campaign_hook,
  portrait_prompt = EXCLUDED.portrait_prompt,
  display_order = EXCLUDED.display_order,
  updated_at = now();
