-- Starter character templates for Curse of the Jersey Devil (5 characters).
-- Follows 20260103_seed_starter_character_templates.sql. Re-runnable: ON CONFLICT upsert on
-- unique_template_per_campaign (starter_campaign_id, template_key).
-- Applied to prod by the Hetzner ingest session on 2026-09-29; see #2226 / #2276 / #2288.
-- This file records that data change and replays it safely.
-- Each row is INSERT ... SELECT FROM starter_campaigns: a no-op where the campaign row is missing
-- (fresh replay), an upsert where it exists. No portrait_url: the asset uploader sets it.
-- Classes are SRD only (starter seeding rejects non-SRD classes). Races use the app's names.

-- 1. The Tracker (Human Ranger)
INSERT INTO public.starter_character_templates (
  starter_campaign_id,
  template_key,
  name,
  tagline,
  race,
  subrace,
  class,
  background,
  level,
  ability_scores,
  personality,
  skills,
  languages,
  equipment,
  adapted_backstory,
  campaign_hook,
  portrait_prompt,
  display_order
) SELECT
  id,
  'the-tracker',
  'The Tracker',
  'Born in the pines; has seen the hoofprints before',
  'Human',
  NULL,
  'Ranger',
  'Outlander',
  1,
  '{"strength": 12, "dexterity": 16, "constitution": 14, "intelligence": 10, "wisdom": 15, "charisma": 9}',
  '{"traits": ["I read the ground before I read a face", "I never whistle in the pines after dark"], "ideals": ["Duty. The Barrens keep their dead; I bring back the living"], "bonds": ["My father followed a line of split hoofprints into the cedar swamp and never came out"], "flaws": ["I do not trust anyone from town, and I let them know it"]}',
  '["survival", "perception", "stealth", "nature"]',
  '["Common", "Sylvan"]',
  '["leather armor", "longbow", "quiver with 20 arrows", "shortsword", "shortsword", "explorer''s pack", "hunting trap"]',
  'I trap muskrat and guide hunters through the Barrens, and I know every sand road and cedar run for thirty miles. When I was twelve my father went after something that took our goats. He left a trail of split hoofprints that ended in the middle of a bog. Nobody believed me then. The farmers around Leeds Point are finding those prints again.',
  'The livestock killings follow Leeds land, and the farmers need a guide who can read the tracks. I take the job for the pay. I stay because the prints are the same size my father''s were.',
  'Lean, weathered human woodsman in a patched oilcloth coat and wide-brimmed hat, longbow over one shoulder, a sprig of cedar tucked in the hatband, sharp wary eyes scanning the trees, crouched beside a split hoofprint in the sand, lantern light from below, twisted pitch pines behind',
  1
FROM public.starter_campaigns
WHERE id = 'curse-of-the-jersey-devil'
ON CONFLICT (starter_campaign_id, template_key) DO UPDATE SET
  name = EXCLUDED.name,
  tagline = EXCLUDED.tagline,
  race = EXCLUDED.race,
  subrace = EXCLUDED.subrace,
  class = EXCLUDED.class,
  background = EXCLUDED.background,
  level = EXCLUDED.level,
  ability_scores = EXCLUDED.ability_scores,
  personality = EXCLUDED.personality,
  skills = EXCLUDED.skills,
  languages = EXCLUDED.languages,
  equipment = EXCLUDED.equipment,
  adapted_backstory = EXCLUDED.adapted_backstory,
  campaign_hook = EXCLUDED.campaign_hook,
  portrait_prompt = EXCLUDED.portrait_prompt,
  display_order = EXCLUDED.display_order,
  updated_at = now();

-- 2. The Circuit Preacher (Human Cleric)
INSERT INTO public.starter_character_templates (
  starter_campaign_id,
  template_key,
  name,
  tagline,
  race,
  subrace,
  class,
  background,
  level,
  ability_scores,
  personality,
  skills,
  languages,
  equipment,
  adapted_backstory,
  campaign_hook,
  portrait_prompt,
  display_order
) SELECT
  id,
  'the-circuit-preacher',
  'The Circuit Preacher',
  'Rides the lonely chapels; carries the bell they need',
  'Human',
  NULL,
  'Cleric',
  'Acolyte',
  1,
  '{"strength": 14, "dexterity": 10, "constitution": 15, "intelligence": 11, "wisdom": 16, "charisma": 12}',
  '{"traits": ["I bless every threshold I cross", "I sing old hymns under my breath when I am afraid"], "ideals": ["Faith. No soul is too far in the pines to be called home"], "bonds": ["Reverend Crane taught me to read from the chapel Bible at Saint Michael''s"], "flaws": ["I believe a sin confessed is a sin forgiven, even when it is not"]}',
  '["religion", "medicine", "insight", "persuasion"]',
  '["Common", "Celestial", "Infernal"]',
  '["scale mail", "mace", "shield", "holy symbol", "priest''s pack", "hand bell"]',
  'I ride the circuit through the Barrens, preaching in chapels too small and too far out to keep a minister of their own. Reverend Josiah Crane took me in when I was a boy and never told me why his hands shake when the wind comes off the cedar swamps. Lately the chapels on my circuit have asked me to bless their barns, their cradles and their doors.',
  'Saint Michael''s Watch sends me to Leeds Point to comfort the families losing livestock. The Reverend gives me one more task, and makes me swear to keep it quiet: keep watch over a young woman named Emma Leeds.',
  'Broad-shouldered human preacher in a dusty black frock coat over scale mail, a heavy hand bell hanging from the belt, holy symbol on a leather cord, kind tired eyes under a flat-crowned hat, mace in one hand, a lantern glowing at his side, a small white clapboard chapel in the dark pines behind him',
  2
FROM public.starter_campaigns
WHERE id = 'curse-of-the-jersey-devil'
ON CONFLICT (starter_campaign_id, template_key) DO UPDATE SET
  name = EXCLUDED.name,
  tagline = EXCLUDED.tagline,
  race = EXCLUDED.race,
  subrace = EXCLUDED.subrace,
  class = EXCLUDED.class,
  background = EXCLUDED.background,
  level = EXCLUDED.level,
  ability_scores = EXCLUDED.ability_scores,
  personality = EXCLUDED.personality,
  skills = EXCLUDED.skills,
  languages = EXCLUDED.languages,
  equipment = EXCLUDED.equipment,
  adapted_backstory = EXCLUDED.adapted_backstory,
  campaign_hook = EXCLUDED.campaign_hook,
  portrait_prompt = EXCLUDED.portrait_prompt,
  display_order = EXCLUDED.display_order,
  updated_at = now();

-- 3. The Almanac-Keeper (Human Wizard)
INSERT INTO public.starter_character_templates (
  starter_campaign_id,
  template_key,
  name,
  tagline,
  race,
  subrace,
  class,
  background,
  level,
  ability_scores,
  personality,
  skills,
  languages,
  equipment,
  adapted_backstory,
  campaign_hook,
  portrait_prompt,
  display_order
) SELECT
  id,
  'the-almanac-keeper',
  'The Almanac-Keeper',
  'Reads the stars, the tides and the family debts',
  'Human',
  NULL,
  'Wizard',
  'Sage',
  1,
  '{"strength": 8, "dexterity": 14, "constitution": 14, "intelligence": 16, "wisdom": 13, "charisma": 11}',
  '{"traits": ["I note the moon''s phase before I agree to anything", "I correct other people''s dates, out loud"], "ideals": ["Knowledge. A debt you cannot read is a debt you cannot pay"], "bonds": ["My spellbook is my grandmother''s almanac, and half its margins are in a hand I do not recognise"], "flaws": ["I cannot leave a locked record room alone"]}',
  '["arcana", "history", "investigation", "religion"]',
  '["Common", "Infernal", "Draconic", "Elvish"]',
  '["quarterstaff", "component pouch", "spellbook", "scholar''s pack", "ink and quill", "brass pocket telescope"]',
  'I print a small almanac for the Barrens towns: planting days, tide tables, eclipses and a few spells hidden in the weather notes for those who can read them. My grandmother kept the same almanac before me. When she died I found her copy of the family tree, with one branch inked out so hard the pen tore the page. The surname under the ink is Leeds.',
  'The Antiquarian Society of Leeds Point wants a scholar to read the old land deeds before the killings drive the families away. I want to know why my grandmother tore my own name out of her book.',
  'Slight human scholar in a worn wool waistcoat with ink-stained cuffs, round spectacles, a thick leather almanac held open in one hand, the other hand raised with a faint ember glow of a spell at the fingertips, star charts and printer''s type on a shelf behind, candlelight from below',
  3
FROM public.starter_campaigns
WHERE id = 'curse-of-the-jersey-devil'
ON CONFLICT (starter_campaign_id, template_key) DO UPDATE SET
  name = EXCLUDED.name,
  tagline = EXCLUDED.tagline,
  race = EXCLUDED.race,
  subrace = EXCLUDED.subrace,
  class = EXCLUDED.class,
  background = EXCLUDED.background,
  level = EXCLUDED.level,
  ability_scores = EXCLUDED.ability_scores,
  personality = EXCLUDED.personality,
  skills = EXCLUDED.skills,
  languages = EXCLUDED.languages,
  equipment = EXCLUDED.equipment,
  adapted_backstory = EXCLUDED.adapted_backstory,
  campaign_hook = EXCLUDED.campaign_hook,
  portrait_prompt = EXCLUDED.portrait_prompt,
  display_order = EXCLUDED.display_order,
  updated_at = now();

-- 4. The Moonshiner (Halfling Rogue)
INSERT INTO public.starter_character_templates (
  starter_campaign_id,
  template_key,
  name,
  tagline,
  race,
  subrace,
  class,
  background,
  level,
  ability_scores,
  personality,
  skills,
  languages,
  equipment,
  adapted_backstory,
  campaign_hook,
  portrait_prompt,
  display_order
) SELECT
  id,
  'the-moonshiner',
  'The Moonshiner',
  'Knows every bog trail the sheriff does not',
  'Halfling',
  'Lightfoot Halfling',
  'Rogue',
  'Criminal',
  1,
  '{"strength": 10, "dexterity": 17, "constitution": 15, "intelligence": 12, "wisdom": 10, "charisma": 13}',
  '{"traits": ["I always know two ways out of a swamp", "I pay my debts in jars, never in coin"], "ideals": ["Freedom. The Barrens belong to those who can live in them"], "bonds": ["The Barrens Folk hid my still from the law for ten years. I owe them"], "flaws": ["I lie to officials on principle, even when the truth would help"]}',
  '["stealth", "sleight_of_hand", "deception", "perception"]',
  '["Common", "Halfling"]',
  '["leather armor", "shortsword", "hand crossbow", "case with 20 crossbow bolts", "thieves'' tools", "burglar''s pack", "copper still coil"]',
  'I run a still on an island in the cedar swamp that no revenue man has ever found. I know the bog trails, the sunken causeways and the dry hummocks where a person can hide for a week. Three nights ago something landed on my still-house roof and stayed there until dawn, breathing. It did not touch me. It watched.',
  'Sheriff Corbin offers to forget my still if I help find the missing Leeds child. I say yes for the deal. I also say yes because I know which way that thing flew when it left my roof.',
  'Stocky halfling bootlegger in a patched canvas jacket and battered felt hat, a clay jug on a cord over one shoulder, hand crossbow at the hip, sly grin and sharp eyes, standing on a mossy log in a dark cedar swamp, a small ember-red lantern glowing beside the boots',
  4
FROM public.starter_campaigns
WHERE id = 'curse-of-the-jersey-devil'
ON CONFLICT (starter_campaign_id, template_key) DO UPDATE SET
  name = EXCLUDED.name,
  tagline = EXCLUDED.tagline,
  race = EXCLUDED.race,
  subrace = EXCLUDED.subrace,
  class = EXCLUDED.class,
  background = EXCLUDED.background,
  level = EXCLUDED.level,
  ability_scores = EXCLUDED.ability_scores,
  personality = EXCLUDED.personality,
  skills = EXCLUDED.skills,
  languages = EXCLUDED.languages,
  equipment = EXCLUDED.equipment,
  adapted_backstory = EXCLUDED.adapted_backstory,
  campaign_hook = EXCLUDED.campaign_hook,
  portrait_prompt = EXCLUDED.portrait_prompt,
  display_order = EXCLUDED.display_order,
  updated_at = now();

-- 5. The Furnace-Born (Half-Orc Fighter)
INSERT INTO public.starter_character_templates (
  starter_campaign_id,
  template_key,
  name,
  tagline,
  race,
  subrace,
  class,
  background,
  level,
  ability_scores,
  personality,
  skills,
  languages,
  equipment,
  adapted_backstory,
  campaign_hook,
  portrait_prompt,
  display_order
) SELECT
  id,
  'the-furnace-born',
  'The Furnace-Born',
  'Descended from the debtors the ironworks buried',
  'Half-Orc',
  NULL,
  'Fighter',
  'Folk Hero',
  1,
  '{"strength": 17, "dexterity": 12, "constitution": 16, "intelligence": 9, "wisdom": 12, "charisma": 10}',
  '{"traits": ["I work with my hands when I need to think", "I stand between the weak and whatever is coming"], "ideals": ["Justice. The Leeds fortune was built on my ancestors'' backs, and someone should answer for it"], "bonds": ["My great-grandmother''s name is carved on a slag-heap marker at the old furnace town"], "flaws": ["I blame the Leeds family for everything, even the ones who did nothing"]}',
  '["athletics", "intimidation", "survival", "perception"]',
  '["Common", "Orc"]',
  '["chain mail", "battleaxe", "shield", "light crossbow", "case with 20 crossbow bolts", "dungeoneer''s pack", "iron slag talisman"]',
  'My people came to the Barrens as debt-bonded furnace workers. They dug the bog iron, fed the furnaces and were buried in the slag heaps without a name on the stone. I grew up among the ruins of the ironworks town, and I have heard the furnaces roar on nights when there is no fire in them. When a Leeds farmer''s barn burned last spring, I carried his children out. He never thanked me.',
  'The killings are spreading from Leeds land to the old furnace country. The families there have no sheriff and no church. They asked me to find out what is hunting them, and I do not say no to my own.',
  'Towering half-orc ironworker in scarred chain mail under a leather smith''s apron, battleaxe resting on one shoulder, shield slung on the back, soot on the forehead, a lump of black slag hanging from a cord at the throat, steady determined eyes, the ember-red glow of a ruined furnace behind',
  5
FROM public.starter_campaigns
WHERE id = 'curse-of-the-jersey-devil'
ON CONFLICT (starter_campaign_id, template_key) DO UPDATE SET
  name = EXCLUDED.name,
  tagline = EXCLUDED.tagline,
  race = EXCLUDED.race,
  subrace = EXCLUDED.subrace,
  class = EXCLUDED.class,
  background = EXCLUDED.background,
  level = EXCLUDED.level,
  ability_scores = EXCLUDED.ability_scores,
  personality = EXCLUDED.personality,
  skills = EXCLUDED.skills,
  languages = EXCLUDED.languages,
  equipment = EXCLUDED.equipment,
  adapted_backstory = EXCLUDED.adapted_backstory,
  campaign_hook = EXCLUDED.campaign_hook,
  portrait_prompt = EXCLUDED.portrait_prompt,
  display_order = EXCLUDED.display_order,
  updated_at = now();
