-- Starter character templates for Wings of the Void (5 characters).
-- Follows 20260103_seed_starter_character_templates.sql. Re-runnable: ON CONFLICT upsert on
-- unique_template_per_campaign (starter_campaign_id, template_key).
-- Applied to prod by the Hetzner ingest session on 2026-09-29; see #2226 / #2276 / #2288.
-- This file records that data change and replays it safely.
-- Each row is INSERT ... SELECT FROM starter_campaigns: a no-op where the campaign row is missing
-- (fresh replay), an upsert where it exists. No portrait_url: the asset uploader sets it.
-- Classes are SRD only (starter seeding rejects non-SRD classes). Races use the app's names.

-- 1. The Rimrunner (Human Rogue)
INSERT INTO public.starter_character_templates (
  starter_campaign_id,
  template_key,
  name,
  tagline,
  race,
  subrace,
  class,
  background,
  level,
  ability_scores,
  personality,
  skills,
  languages,
  equipment,
  adapted_backstory,
  campaign_hook,
  portrait_prompt,
  display_order
) SELECT
  id,
  'the-rimrunner',
  'The Rimrunner',
  'Jumped off Beggar''s Ledge for coins; now jumps for the world',
  'Human',
  NULL,
  'Rogue',
  'Urchin',
  1,
  '{"strength": 10, "dexterity": 17, "constitution": 14, "intelligence": 11, "wisdom": 12, "charisma": 13}',
  '{"traits": ["I count the seconds of every fall out loud", "I always know which way the wind is about to turn"], "ideals": ["Freedom. The sky belongs to anyone brave enough to step off"], "bonds": ["The ledge kids who taught me to jump still owe me, and I still owe them"], "flaws": ["I take the jump before I finish the plan"]}',
  '["acrobatics", "stealth", "sleight_of_hand", "perception"]',
  '["Common"]',
  '["leather armor", "shortsword", "dagger", "dagger", "thieves'' tools", "burglar''s pack", "patched wingsuit"]',
  'I grew up on Beggar''s Ledge, where kids dive off the Rim for coins the tourists throw. Most of us learned to open a chute before we learned to read. The Fallers watched me for a year before they offered me a place. I said yes before they finished asking.',
  'Tonight is my initiation jump at the Nest. Skydancer Kaia herself will watch. I have fallen a thousand times for money. This is the first time I fall for something bigger than me.',
  'Wiry young human in a patched, many-times-mended wingsuit with the arm membranes folded, goggles pushed up into wind-tangled hair, a coin on a cord at the throat, crouched on the edge of a rusted gantry above a bottomless glowing rift, grinning, strong wind pulling at the fabric',
  1
FROM public.starter_campaigns
WHERE id = 'wings-of-the-void'
ON CONFLICT (starter_campaign_id, template_key) DO UPDATE SET
  name = EXCLUDED.name,
  tagline = EXCLUDED.tagline,
  race = EXCLUDED.race,
  subrace = EXCLUDED.subrace,
  class = EXCLUDED.class,
  background = EXCLUDED.background,
  level = EXCLUDED.level,
  ability_scores = EXCLUDED.ability_scores,
  personality = EXCLUDED.personality,
  skills = EXCLUDED.skills,
  languages = EXCLUDED.languages,
  equipment = EXCLUDED.equipment,
  adapted_backstory = EXCLUDED.adapted_backstory,
  campaign_hook = EXCLUDED.campaign_hook,
  portrait_prompt = EXCLUDED.portrait_prompt,
  display_order = EXCLUDED.display_order,
  updated_at = now();

-- 2. The Rigger (Dwarf Fighter)
INSERT INTO public.starter_character_templates (
  starter_campaign_id,
  template_key,
  name,
  tagline,
  race,
  subrace,
  class,
  background,
  level,
  ability_scores,
  personality,
  skills,
  languages,
  equipment,
  adapted_backstory,
  campaign_hook,
  portrait_prompt,
  display_order
) SELECT
  id,
  'the-rigger',
  'The Rigger',
  'Stitches the wings that everyone else trusts with their lives',
  'Dwarf',
  'Hill Dwarf',
  'Fighter',
  'Guild Artisan',
  1,
  '{"strength": 16, "dexterity": 12, "constitution": 16, "intelligence": 13, "wisdom": 12, "charisma": 8}',
  '{"traits": ["I inspect every seam on every wingsuit I see, even strangers''", "I name each rig I build and never sell the first one"], "ideals": ["Craft. A good stitch is a promise kept at ten thousand feet"], "bonds": ["A rig I built failed once. I will not let it happen again"], "flaws": ["I do not trust any gear I did not make myself"]}',
  '["athletics", "insight", "perception", "survival"]',
  '["Common", "Dwarvish"]',
  '["chain mail", "warhammer", "shield", "light crossbow", "dungeoneer''s pack", "rigger''s needle roll"]',
  'I stitched wingsuits in the Rusty Gantry for twenty years, from Void Glider membrane and cable thread. Half the Fallers alive owe their lives to my seams. The other half did not buy from me. I have never jumped. The Council says the Barrier will end the Descents, and with them, my trade and my friends.',
  'Kaia asked me to rig the new initiates and then, to my shock, to jump with them. If my stitches are going into the Abyss, I am going with them.',
  'Stocky hill dwarf with a braided grey-streaked beard, a heavy leather work apron over chain mail, a coil of cable thread and a steel needle roll on the chest strap, holding a half-finished wingsuit wing across both arms, goggles on the forehead, workshop lamps glowing behind',
  2
FROM public.starter_campaigns
WHERE id = 'wings-of-the-void'
ON CONFLICT (starter_campaign_id, template_key) DO UPDATE SET
  name = EXCLUDED.name,
  tagline = EXCLUDED.tagline,
  race = EXCLUDED.race,
  subrace = EXCLUDED.subrace,
  class = EXCLUDED.class,
  background = EXCLUDED.background,
  level = EXCLUDED.level,
  ability_scores = EXCLUDED.ability_scores,
  personality = EXCLUDED.personality,
  skills = EXCLUDED.skills,
  languages = EXCLUDED.languages,
  equipment = EXCLUDED.equipment,
  adapted_backstory = EXCLUDED.adapted_backstory,
  campaign_hook = EXCLUDED.campaign_hook,
  portrait_prompt = EXCLUDED.portrait_prompt,
  display_order = EXCLUDED.display_order,
  updated_at = now();

-- 3. The Cartographer (Gnome Wizard)
INSERT INTO public.starter_character_templates (
  starter_campaign_id,
  template_key,
  name,
  tagline,
  race,
  subrace,
  class,
  background,
  level,
  ability_scores,
  personality,
  skills,
  languages,
  equipment,
  adapted_backstory,
  campaign_hook,
  portrait_prompt,
  display_order
) SELECT
  id,
  'the-cartographer',
  'The Cartographer',
  'Maps a place that refuses to hold still',
  'Gnome',
  'Rock Gnome',
  'Wizard',
  'Sage',
  1,
  '{"strength": 8, "dexterity": 14, "constitution": 14, "intelligence": 16, "wisdom": 13, "charisma": 10}',
  '{"traits": ["I measure every drop in seconds, meters and heartbeats", "I talk to my altimeter as if it can hear me"], "ideals": ["Knowledge. A true chart of the Abyss saves more lives than any sword"], "bonds": ["My mentor''s last chart ends at five kilometers. I mean to finish it"], "flaws": ["I will dive deeper than is safe to fill one blank space on a map"]}',
  '["arcana", "history", "investigation", "insight"]',
  '["Common", "Gnomish", "Primordial", "Celestial"]',
  '["quarterstaff", "component pouch", "spellbook", "scholar''s pack", "brass altimeter", "waxed chart case"]',
  'The Vertical Cartographers Guild sent me to chart the Twilight Zone. Maps of the Abyss drift and lie: distances stretch, and north turns into down. My mentor vanished below five kilometers with the only chart that went deeper. The Fallers go where the Guild will not.',
  'To follow my mentor''s route, I need to learn to fall. The Fallers need someone who can read a map that changes. We made a deal at the Nest, and tonight I take my first jump.',
  'Small bright-eyed rock gnome in a fitted flight jacket covered in pockets and pencils, a brass altimeter strapped to one wrist, a rolled chart under one arm, round goggles with a cracked lens, a faint violet arcane glow at the fingertips, clouds and a glowing rift far below',
  3
FROM public.starter_campaigns
WHERE id = 'wings-of-the-void'
ON CONFLICT (starter_campaign_id, template_key) DO UPDATE SET
  name = EXCLUDED.name,
  tagline = EXCLUDED.tagline,
  race = EXCLUDED.race,
  subrace = EXCLUDED.subrace,
  class = EXCLUDED.class,
  background = EXCLUDED.background,
  level = EXCLUDED.level,
  ability_scores = EXCLUDED.ability_scores,
  personality = EXCLUDED.personality,
  skills = EXCLUDED.skills,
  languages = EXCLUDED.languages,
  equipment = EXCLUDED.equipment,
  adapted_backstory = EXCLUDED.adapted_backstory,
  campaign_hook = EXCLUDED.campaign_hook,
  portrait_prompt = EXCLUDED.portrait_prompt,
  display_order = EXCLUDED.display_order,
  updated_at = now();

-- 4. The Windspeaker (Half-Elf Cleric)
INSERT INTO public.starter_character_templates (
  starter_campaign_id,
  template_key,
  name,
  tagline,
  race,
  subrace,
  class,
  background,
  level,
  ability_scores,
  personality,
  skills,
  languages,
  equipment,
  adapted_backstory,
  campaign_hook,
  portrait_prompt,
  display_order
) SELECT
  id,
  'the-windspeaker',
  'The Windspeaker',
  'Hears prayers in the updrafts and answers them',
  'Half-Elf',
  NULL,
  'Cleric',
  'Acolyte',
  1,
  '{"strength": 12, "dexterity": 12, "constitution": 14, "intelligence": 10, "wisdom": 16, "charisma": 14}',
  '{"traits": ["I bless every jumper before they step off the edge", "I hum under my breath in freefall"], "ideals": ["Faith. The fall is a prayer, and the Abyss is listening"], "bonds": ["I left the Anchorites because I believe the Void can be healed, not only held back"], "flaws": ["I trust the wind more than I trust people"]}',
  '["religion", "medicine", "insight", "persuasion"]',
  '["Common", "Elvish", "Celestial"]',
  '["scale mail", "mace", "shield", "holy symbol", "priest''s pack", "wind-chime charm"]',
  'I was raised among the Anchorites, who tie themselves to stone and pray that nothing falls. I began to hear something else in the updrafts: voices, asking for help. The Anchorites called it heresy. The Fallers called it a calling.',
  'Skydancer Kaia says the voices I hear come from the Void''s refugees. If the Council''s Barrier closes, those voices go silent forever. I jump to hear them clearly.',
  'Calm half-elf priest in a flowing layered flight robe tied close for the jump, a holy symbol of a stylised updraft on a cord, small wind chimes braided into long hair, eyes closed as if listening, one hand raised into the wind, soft light rising from the glowing rift below',
  4
FROM public.starter_campaigns
WHERE id = 'wings-of-the-void'
ON CONFLICT (starter_campaign_id, template_key) DO UPDATE SET
  name = EXCLUDED.name,
  tagline = EXCLUDED.tagline,
  race = EXCLUDED.race,
  subrace = EXCLUDED.subrace,
  class = EXCLUDED.class,
  background = EXCLUDED.background,
  level = EXCLUDED.level,
  ability_scores = EXCLUDED.ability_scores,
  personality = EXCLUDED.personality,
  skills = EXCLUDED.skills,
  languages = EXCLUDED.languages,
  equipment = EXCLUDED.equipment,
  adapted_backstory = EXCLUDED.adapted_backstory,
  campaign_hook = EXCLUDED.campaign_hook,
  portrait_prompt = EXCLUDED.portrait_prompt,
  display_order = EXCLUDED.display_order,
  updated_at = now();

-- 5. The Deserter (Half-Orc Ranger)
INSERT INTO public.starter_character_templates (
  starter_campaign_id,
  template_key,
  name,
  tagline,
  race,
  subrace,
  class,
  background,
  level,
  ability_scores,
  personality,
  skills,
  languages,
  equipment,
  adapted_backstory,
  campaign_hook,
  portrait_prompt,
  display_order
) SELECT
  id,
  'the-deserter',
  'The Deserter',
  'Walked away from the Sky Council patrol with one wingsuit and no regrets',
  'Half-Orc',
  NULL,
  'Ranger',
  'Soldier',
  1,
  '{"strength": 15, "dexterity": 15, "constitution": 14, "intelligence": 10, "wisdom": 14, "charisma": 8}',
  '{"traits": ["I still salute out of habit, then hate myself for it", "I check every exit and every updraft before I relax"], "ideals": ["Responsibility. I helped build the Barrier; I will help stop it"], "bonds": ["My old patrol squad still flies for the Council. I will not shoot at them"], "flaws": ["I keep secrets about what the Council plans, even from my friends"]}',
  '["survival", "perception", "athletics", "intimidation"]',
  '["Common", "Orc"]',
  '["scale mail", "longbow", "quiver with 20 arrows", "shortsword", "shortsword", "explorer''s pack", "Council patrol insignia"]',
  'I flew Barrier patrol for the Sky Council for six years, hunting Void creatures and Fallers alike. Then I saw what the Barrier will do to the refugees trapped behind it. I took my patrol wingsuit and jumped the other way.',
  'The Council calls me a deserter and a traitor. The Fallers call me a risk. Kaia called me useful. I know the Barrier''s schedule, and I know it is ahead of what anyone thinks.',
  'Broad-shouldered half-orc in a scuffed military wingsuit with the Sky Council insignia torn off one shoulder, a longbow slung across the back, a scar across one tusk, steady watchful eyes, standing on a wind-battered ledge with a stormy sky and the glowing rift behind',
  5
FROM public.starter_campaigns
WHERE id = 'wings-of-the-void'
ON CONFLICT (starter_campaign_id, template_key) DO UPDATE SET
  name = EXCLUDED.name,
  tagline = EXCLUDED.tagline,
  race = EXCLUDED.race,
  subrace = EXCLUDED.subrace,
  class = EXCLUDED.class,
  background = EXCLUDED.background,
  level = EXCLUDED.level,
  ability_scores = EXCLUDED.ability_scores,
  personality = EXCLUDED.personality,
  skills = EXCLUDED.skills,
  languages = EXCLUDED.languages,
  equipment = EXCLUDED.equipment,
  adapted_backstory = EXCLUDED.adapted_backstory,
  campaign_hook = EXCLUDED.campaign_hook,
  portrait_prompt = EXCLUDED.portrait_prompt,
  display_order = EXCLUDED.display_order,
  updated_at = now();
