import { Edit3, Save, X, Sparkles } from 'lucide-react';
import React, { useState, useRef, useEffect, useId } from 'react';

import type { Character, CharacterSheetUpdateFn } from '@/types/character';

import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from '@/components/ui/tooltip';
import { useToast } from '@/hooks/use-toast';
import { cn } from '@/lib/utils';

export interface EditableDescriptionProps {
  /** The current value of the description field */
  value: string;
  /** The label to display above the field */
  label: string;
  /** Placeholder text when the field is empty */
  placeholder: string;
  /** The field name in the character object */
  field: keyof Character;
  /** The character object */
  character: Character;
  /** Callback that persists the updated character; resolves true on success */
  onUpdate: CharacterSheetUpdateFn;
  /** Whether this field was generated by AI */
  isAiGenerated?: boolean;
  /** Additional CSS classes */
  className?: string;
  /** Minimum height for the textarea */
  minHeight?: string;
  /** Whether the component is disabled */
  disabled?: boolean;
}

/**
 * EditableDescription Component
 *
 * A reusable component for editing character description fields that can toggle
 * between read-only and editable modes. Shows visual indicators for AI-generated content.
 *
 * Features:
 * - Toggle between read-only and edit modes
 * - Auto-resize textarea based on content
 * - AI generation indicator badge
 * - Save/Cancel functionality
 * - Proper TypeScript types
 * - Consistent with project styling patterns
 */
const EditableDescription: React.FC<EditableDescriptionProps> = ({
  value = '',
  label,
  placeholder,
  field,
  character,
  onUpdate,
  isAiGenerated = false,
  className,
  minHeight = 'min-h-[100px]',
  disabled = false,
}) => {
  const [isEditing, setIsEditing] = useState(false);
  const [editValue, setEditValue] = useState(value);
  const { toast } = useToast();
  const textareaRef = useRef<HTMLTextAreaElement>(null);
  const textareaId = useId();

  // Auto-resize textarea
  useEffect(() => {
    const textarea = textareaRef.current;
    if (textarea && isEditing) {
      textarea.style.height = 'auto';
      textarea.style.height = `${textarea.scrollHeight}px`;
    }
  }, [editValue, isEditing]);

  // Reset edit value when value prop changes
  useEffect(() => {
    setEditValue(value);
  }, [value]);

  // Focus textarea when entering edit mode
  useEffect(() => {
    if (isEditing && textareaRef.current) {
      textareaRef.current.focus();
      // Move cursor to end
      const length = textareaRef.current.value.length;
      textareaRef.current.setSelectionRange(length, length);
    }
  }, [isEditing]);

  const handleEdit = () => {
    if (!disabled) {
      setIsEditing(true);
    }
  };

  // #2701: save awaits the write. On success the editor closes and confirms;
  // on failure it stays open so the user can retry (the persistence layer
  // already toasted the error).
  const handleSave = async () => {
    const saved = await onUpdate({
      ...character,
      [field]: editValue,
    });
    if (!saved) {
      return;
    }
    setIsEditing(false);
    toast({ title: `${label} saved` });
  };

  const handleCancel = () => {
    setEditValue(value);
    setIsEditing(false);
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Escape') {
      handleCancel();
    } else if (e.key === 'Enter' && (e.ctrlKey || e.metaKey)) {
      handleSave();
    }
  };

  const handleDisplayKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' || e.key === ' ') {
      e.preventDefault();
      handleEdit();
    }
  };

  const handleTextareaChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    setEditValue(e.target.value);
    // Auto-resize
    e.target.style.height = 'auto';
    e.target.style.height = `${e.target.scrollHeight}px`;
  };

  return (
    <TooltipProvider>
      <div className={cn('space-y-2', className)}>
        {/* Label and AI Badge Row */}
        <div className="flex items-center justify-between">
          <Label
            id={`${textareaId}-label`}
            htmlFor={isEditing ? textareaId : undefined}
            className="text-sm font-medium text-muted-foreground"
          >
            {label}
          </Label>
          <div className="flex items-center gap-2">
            {isAiGenerated && !isEditing && (
              <Badge
                variant="outline"
                className="text-xs bg-infinite-purple/15 border-infinite-purple/30 text-infinite-purple"
              >
                <Sparkles className="w-3 h-3 mr-1" />
                Generated by AI
              </Badge>
            )}
            {!isEditing && (
              <Tooltip>
                <TooltipTrigger asChild>
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={handleEdit}
                    disabled={disabled}
                    className="h-6 w-6 p-0 hover:bg-accent"
                    aria-label={`Edit ${label}`}
                  >
                    <Edit3 className="w-3 h-3" />
                  </Button>
                </TooltipTrigger>
                <TooltipContent>
                  <p>Edit {label}</p>
                </TooltipContent>
              </Tooltip>
            )}
          </div>
        </div>

        {/* Content Area */}
        {isEditing ? (
          <div className="space-y-2">
            <Textarea
              id={textareaId}
              ref={textareaRef}
              value={editValue}
              onChange={handleTextareaChange}
              onKeyDown={handleKeyDown}
              placeholder={placeholder}
              className={cn(
                minHeight,
                'resize-none transition-all duration-200 focus:ring-2 focus:ring-primary/20',
              )}
              rows={3}
            />
            <div className="flex items-center justify-end gap-2">
              <Tooltip>
                <TooltipTrigger asChild>
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={handleCancel}
                    className="h-8 px-3"
                    aria-label="Cancel editing"
                  >
                    <X className="w-3 h-3 mr-1" />
                    Cancel
                  </Button>
                </TooltipTrigger>
                <TooltipContent>
                  <p>Cancel editing</p>
                </TooltipContent>
              </Tooltip>
              <Tooltip>
                <TooltipTrigger asChild>
                  <Button
                    variant="default"
                    size="sm"
                    onClick={handleSave}
                    className="h-8 px-3"
                    aria-label={`Save ${label}`}
                  >
                    <Save className="w-3 h-3 mr-1" />
                    Save
                  </Button>
                </TooltipTrigger>
                <TooltipContent>
                  <p>Save {label}</p>
                </TooltipContent>
              </Tooltip>
            </div>
            <div className="text-xs text-muted-foreground">
              Press Ctrl+Enter to save, Escape to cancel
            </div>
          </div>
        ) : (
          <Tooltip>
            <TooltipTrigger asChild>
              <div
                className={cn(
                  'relative rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background transition-colors outline-none focus-visible:ring-2 focus-visible:ring-primary/20',
                  minHeight,
                  'hover:bg-accent/50 cursor-pointer group',
                  disabled && 'opacity-50 cursor-not-allowed hover:bg-background',
                )}
                onClick={handleEdit}
                onKeyDown={handleDisplayKeyDown}
                role="button"
                tabIndex={disabled ? -1 : 0}
                aria-label={`Click to edit ${label}`}
              >
                {value ? (
                  <div className="whitespace-pre-wrap break-words leading-relaxed">{value}</div>
                ) : (
                  <div className="text-muted-foreground italic">{placeholder}</div>
                )}

                {/* Hover Edit Indicator */}
                {!disabled && (
                  <div className="absolute top-2 right-2 opacity-0 group-hover:opacity-100 transition-opacity">
                    <Edit3 className="w-3 h-3 text-muted-foreground" />
                  </div>
                )}
              </div>
            </TooltipTrigger>
            <TooltipContent>
              <p>Click to edit {label}</p>
            </TooltipContent>
          </Tooltip>
        )}
      </div>
    </TooltipProvider>
  );
};

export default EditableDescription;
