#!/usr/bin/env bash
# =============================================================================
# Schema Drift Guard
# =============================================================================
# Fails when db/schema/*.ts has been edited without a matching migration in
# db/migrations/.
#
# Why: three separate production incidents (20260710 character_equipment,
# 20260725 exhaustion_level plus eleven entirely-missing tables) all came from
# the same root cause -- a drizzle schema file was edited, the code shipped,
# and no migration was ever written. Nothing in CI compared the two, so the
# only detection mechanism was a 500 in production. See 17ebfd47 for the full
# writeup.
#
# How: drizzle-kit `generate` diffs db/schema/*.ts against the newest snapshot
# in db/migrations/meta/. If they agree it writes nothing; if they disagree it
# emits a migration. This script runs generate against a scratch *copy* of
# db/migrations/ and fails if anything was emitted, so the check never mutates
# the repo -- not even on a drift-detecting run.
#
# Two drizzle-kit sharp edges this script exists to work around:
#   1. `drizzle-kit check` is NOT a drift check. It only looks for collisions
#      and corruption *within* the snapshot chain, and cheerfully reports
#      "Everything's fine" against a schema.ts that has drifted by 45 tables.
#      Verified against drizzle-kit 0.31.10.
#   2. `--out` with an absolute path is silently mis-resolved (drizzle-kit
#      prefixes it with './'), which makes generate report "no changes" for
#      real drift. Hence the scratch dir lives inside the project and is
#      addressed by a generated relative-path config.
#
# Usage:
#   bun run db:check-drift          # or: bash scripts/check-schema-drift.sh
#
# Exit codes: 0 = no drift, 1 = drift detected, 2 = unable to run the check.
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
cd "$PROJECT_ROOT"

MIGRATIONS_DIR="db/migrations"
# Must be inside the project: drizzle-kit cannot address an absolute out dir.
# Listed in .gitignore so a crashed run cannot pollute `git status`.
SCRATCH_DIR=".drizzle-drift-check"

RED=$'\033[0;31m'
GREEN=$'\033[0;32m'
CYAN=$'\033[0;36m'
NC=$'\033[0m'

cleanup() { rm -rf "$SCRATCH_DIR"; }
trap cleanup EXIT

# bunx can download a temporary drizzle-kit binary when this worktree has no
# dependencies. That binary cannot load the repo's local config, and its error
# used to be reported by pre-push as phantom schema drift. Require the local
# install and return a distinct status before attempting the check.
if [ ! -d "$PROJECT_ROOT/node_modules" ] || \
   [ ! -x "$PROJECT_ROOT/node_modules/.bin/drizzle-kit" ] || \
   ! (cd "$PROJECT_ROOT" && bun -e "await import('drizzle-kit')") >/dev/null 2>&1; then
  echo "${RED}✗${NC} Could not run schema drift check: cannot resolve drizzle-kit (node_modules missing — run bun install or symlink $PROJECT_ROOT/node_modules)." >&2
  exit 2
fi

if [ ! -d "$MIGRATIONS_DIR/meta" ]; then
  echo "${RED}✗${NC} Could not run schema drift check: $MIGRATIONS_DIR/meta not found -- is drizzle initialised?" >&2
  exit 2
fi

rm -rf "$SCRATCH_DIR"
mkdir -p "$SCRATCH_DIR"
cp -R "$MIGRATIONS_DIR" "$SCRATCH_DIR/migrations"
# On macOS, copying onto a filesystem without native extended-attribute support
# (exFAT/FAT external drives) writes an AppleDouble `._name` sidecar next to every
# file. drizzle-kit then reads `._0000_snapshot.json` as a snapshot, and the
# resulting parse failure surfaces as phantom drift on a tree that has none.
find "$SCRATCH_DIR/migrations" -name '._*' -delete

cat >"$SCRATCH_DIR/drizzle.config.ts" <<'CONFIG'
// Generated by scripts/check-schema-drift.sh. Do not edit; do not commit.
// Mirrors ../drizzle.config.ts but writes into the scratch migrations copy.
import { defineConfig } from 'drizzle-kit';

export default defineConfig({
  dialect: 'postgresql',
  schema: './db/schema/*.ts',
  out: './.drizzle-drift-check/migrations',
  breakpoints: true,
});
CONFIG

echo "${CYAN}ℹ${NC} Diffing db/schema/*.ts against $MIGRATIONS_DIR/meta ..."

GENERATE_LOG="$SCRATCH_DIR/generate.log"
set +e
bunx drizzle-kit generate \
  --config "$SCRATCH_DIR/drizzle.config.ts" \
  --name schema_drift_check >"$GENERATE_LOG" 2>&1
GENERATE_STATUS=$?
set -e

if [ $GENERATE_STATUS -ne 0 ]; then
  echo "${RED}✗${NC} Could not run schema drift check: drizzle-kit generate failed (exit $GENERATE_STATUS):" >&2
  cat "$GENERATE_LOG" >&2
  exit 2
fi

# Any .sql drizzle-kit emitted into the scratch copy is DDL that db/schema/*.ts
# requires and no migration in db/migrations/ provides.
EMITTED="$(comm -13 \
  <(find "$MIGRATIONS_DIR" -maxdepth 1 -name '*.sql' -exec basename {} \; | sort) \
  <(find "$SCRATCH_DIR/migrations" -maxdepth 1 -name '*.sql' -exec basename {} \; | sort))"

if [ -z "$EMITTED" ]; then
  echo "${GREEN}✓${NC} No schema drift: db/schema/*.ts matches db/migrations/."
  exit 0
fi

{
  echo ""
  echo "${RED}✗ SCHEMA DRIFT DETECTED${NC}"
  echo ""
  echo "db/schema/*.ts declares structure that no migration in db/migrations/ creates."
  echo "Shipping this means code queries columns production does not have -- the exact"
  echo "failure mode of the 20260725 exhaustion_level incident (see 17ebfd47)."
  echo ""
  echo "Missing DDL:"
  echo ""
  while IFS= read -r sql; do
    [ -n "$sql" ] || continue
    awk '{ print "    " $0 }' "$SCRATCH_DIR/migrations/$sql"
  done <<<"$EMITTED"
  echo ""
  echo "To fix, from ai-adventure-scribe-main/:"
  echo ""
  echo "    bunx drizzle-kit generate --name <describe_your_change>"
  echo ""
  echo "Then review the emitted db/migrations/*.sql -- drizzle's DDL is a starting"
  echo "point, not gospel; add backfills, defaults and NOT NULL ordering by hand --"
  echo "and commit it in the same commit as the db/schema/*.ts edit. Hand-written"
  echo "migrations are fine too, as long as you also commit the refreshed"
  echo "db/migrations/meta/ snapshot that drizzle-kit generate produces."
  echo ""
} >&2

exit 1
